### ISSUE TITLE
zaboy\rest\Middleware\RequestDecoder

### ISSUE THREAD

**Issue by victorynox** [avz-cmf/zaboy-rest#1]
Нет проверки на существование массива 
`$overwriteMode = $overwriteModeHeader[0] === '*' ? true : false;`

`if (false !== strpos($contenttype[0], 'json')) {
$body = $this->jsonDecode($request->getBody()->__toString());
$request = $request->withParsedBody($body);
} else {
 //todo XML?
}`

**Comment by avz-cmf** [comment]
Fixed
