### ISSUE TITLE
zaboy\rest\Pipes\Factory\RestPipeFactory 

### ISSUE THREAD

**Issue by victorynox** [avz-cmf/zaboy-rest#2]
в конструкторе нужно добавить еще одну переменную, так как sm передает 3 параметра
`public function __invoke(ContainerInterface $container, $requestedName, $requestedNameSpace, array $options = null) {...}
`

**Comment by avz-cmf** [comment]
https://github.com/avz-cmf/zaboy-rest/issues/3#issuecomment-192848554
