### ISSUE TITLE
zaboy\rest\Middlewares\Factory\StoreMiddlewareFactory

### ISSUE THREAD

**Issue by victorynox** [avz-cmf/zaboy-rest#3]
в конструкторе нужно добавить еще одну переменную, так как sm передает 3 параметра
`public function __invoke(ContainerInterface $container, $requestedName, $requestedNameSpace, array $options = null) {...}
`

**Comment by avz-cmf** [comment]
https://github.com/zendframework/zend-servicemanager/blob/release-3.0.3/src/Factory/AbstractFactoryInterface.php

https://github.com/zendframework/zend-servicemanager/blob/release-3.0.3/src/Factory/FactoryInterface.php

```
public function __invoke(ContainerInterface $container, $requestedName, array $options = null);
```

}

Где третий параметр?

**Comment by victorynox** [comment]
У нас ServiceManager 2.7
[ServiceManager 2.7](https://github.com/zendframework/zend-servicemanager/tree/release-2.7/src)

там нет Factory/FactoryInterface.php и Factory/AbstractFactoryInterface.php
там создание происходит в методе 
`protected function createServiceViaCallback($callable, $cName, $rName)`
вызов `$instance = call_user_func($callable, $this, $cName, $rName);`
