### ISSUE TITLE
 zaboy\rest\Middleware\RqlParser

### ISSUE THREAD

**Issue by victorynox** [avz-cmf/zaboy-rest#5]
В методе __invoke когда передаете query  `$tokens = $this->lexer->tokenize($rqlQueryString);`,
`$rqlQueryString` - стоит обернуть в `urldecode()` 
 `$tokens = $this->lexer->tokenize(urldecode($rqlQueryString));`, что бы декодировать спец символы

**Comment by avz-cmf** [comment]
done
